-- 코드를 작성해주세요

SELECT ED.ID, IFNULL(ED2.CHILD_COUNT,0) CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN 
    (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL    
    ) ED2
ON ED.ID = ED2.PARENT_ID
ORDER BY ID

