-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM ANIMAL_INS AI
WHERE ANIMAL_ID NOT IN ( SELECT ANIMAL_ID FROM ANIMAL_OUTS) AND
      DATETIME >= ( SELECT MIN(DATETIME) FROM ANIMAL_INS)
ORDER BY DATETIME
LIMIT 3