-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, PRODUCT_NAME, (SALES * PRICE) TOTAL_SALES
FROM FOOD_PRODUCT FD
JOIN
    (
    SELECT PRODUCT_ID, SUM(AMOUNT) SALES
    FROM FOOD_ORDER  
    WHERE PRODUCE_DATE LIKE "2022-05%"
    GROUP BY PRODUCT_ID
    ) FO
ON FD.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
