-- 코드를 입력하세요
SELECT FLAVOR
FROM ( SELECT FH.FLAVOR, (FH.TOTAL_ORDER + J.TOTAL_ORDER) TOTAL_ORDER
       FROM ( SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM FIRST_HALF GROUP BY FLAVOR ) FH
       JOIN ( SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM JULY GROUP BY FLAVOR ) J
       ON FH.FLAVOR = J.FLAVOR
       GROUP BY FH.FLAVOR
       ORDER BY TOTAL_ORDER DESC ) A
LIMIT 3
