-- 코드를 작성해주세요

SELECT ED2.YEAR YEAR, ( ED2.MAX_SIZE - ED.SIZE_OF_COLONY ) YEAR_DEV, ED.ID ID
FROM ECOLI_DATA ED
JOIN ( SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
       FROM ECOLI_DATA 
       GROUP BY YEAR
    ) ED2
ON YEAR(ED.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY YEAR, YEAR_DEV